version: '2'
services:
  db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=permanent_make_up_rwx
      - MYSQL_PASSWORD=ekl84
      - MYSQL_DATABASE=main
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
