apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-service
  name: admin-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: admin-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-service
  name: admin-service
spec:
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      volumes:
      - name: credentials
        secret:
          secretName: permanent-make-up-service-account
      containers:
      - name: admin-service
        image: gcr.io/permanent-make-up/admin-service:latest
        volumeMounts:
        - name: credentials
          mountPath: "/etc/credentials"
          readOnly: true
        env:
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          value: "true"
        - name: EUREKA_SERVICE_URL
          value: "http://admin-service:8761"
        ports:
        - name: http
          containerPort: 8081