apiVersion: v1
kind: Pod
metadata:
  name: admin
  labels:
    app: spring-boot-admin
    component: admin
spec:
  containers:
    - image: gcr.io/permanent-make-up/admin-service
      name: spring-boot-admin
      ports:
        - containerPort: 8081
      env:
        - name: EUREKA_SERVICE_URL
          value: "http://eureka:8761" #"eureka" host is resolved by K8s DNS matching the service name
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
    - port: 8081
  selector:
    app: spring-boot-admin
    component: admin
  type: LoadBalancer