apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: backend-service
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: backend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-service
  name: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      volumes:
      - name: credentials
        secret:
          secretName: permanent-make-up-service-account
      containers:
      - name: backend-service
        image: gcr.io/permanent-make-up/frontend-service
        volumeMounts:
        - name: credentials
          mountPath: "/etc/credentials"
          readOnly: true
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/project-editor.json
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        ports:
        - name: http
          containerPort: 8082