apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-service
  name: eureka-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    app: eureka-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-service
  name: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: gcr.io/permanent-make-up/eureka-service
        env:
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          value: "true"
        ports:
        - name: http
          containerPort: 8761