apiVersion: v1
kind: Pod
metadata:
  name: eureka
  labels:
    app: spring-boot-admin
    component: eureka
spec:
  containers:
    - name: eureka
      image: gcr.io/permanent-make-up/eureka-service
      ports:
        - containerPort: 8761
      env:
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  ports:
    - port: 8761
  selector:
    app: spring-boot-admin
    component: eureka
  type: LoadBalancer